#!/usr/bin/env php
<?php
/**
 * Repoman
 *
 * Command line tool for managing MODX Revo dev projects in the local environment.
 * Place this script anywhere inside your MODX web root.
 *
 * See https://github.com/craftsmancoding/repoman/ for full documentation or use
 * the "help" command
 *
 * USAGE
 * -------
 *
 * php repoman <function> [arguments]
 *
 * php repoman help [function-name]
 *
 */
require_once dirname(__FILE__).'/vendor/autoload.php';

use Repoman\Console\Command\Build;
use Repoman\Console\Command\Create;
use Repoman\Console\Command\Export;
use Repoman\Console\Command\Graph;
use Repoman\Console\Command\Help;
use Repoman\Console\Command\Import;
use Repoman\Console\Command\Install;
use Repoman\Console\Command\Migrate;
use Repoman\Console\Command\SchemaWrite;
use Repoman\Console\Command\SchemaParse;
use Repoman\Console\Command\Seed;
use Repoman\Console\Command\Update;
use Repoman\Console\Command\Uninstall;
use Symfony\Component\Console\Application;

$application = new Application('Repoman CLI', '1.0');
$application->add(new Build());
$application->add(new Create());
$application->add(new Export());
$application->add(new Graph());
//$application->add(new Help());  // How to augment the default generated stuff?
$application->add(new Import());
$application->add(new Install());
$application->add(new Migrate());
$application->add(new SchemaWrite());
$application->add(new SchemaParse());
$application->add(new Seed());
$application->add(new Uninstall());
$application->add(new Update());
$application->run();
/*EOF*/
