<?php
return array(
    array("code"=>"ALL","name"=>"Albania Lek","symbol"=>"76","is_active"=>0),
    array("code"=>"AFN","name"=>"Afghanistan Afghani","symbol"=>"1547","is_active"=>0),
    array("code"=>"ARS","name"=>"Argentina Peso","symbol"=>"36","is_active"=>0),
    array("code"=>"AWG","name"=>"Aruba Guilder","symbol"=>"402","is_active"=>0),
    array("code"=>"AUD","name"=>"Australia Dollar","symbol"=>"36","is_active"=>1),
    array("code"=>"AZN","name"=>"Azerbaijan New Manat","symbol"=>"1084","is_active"=>0),
    array("code"=>"BSD","name"=>"Bahamas Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"BBD","name"=>"Barbados Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"BYR","name"=>"Belarus Ruble","symbol"=>"112","is_active"=>0),
    array("code"=>"BZD","name"=>"Belize Dollar","symbol"=>"66","is_active"=>0),
    array("code"=>"BMD","name"=>"Bermuda Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"BOB","name"=>"Bolivia Boliviano","symbol"=>"36","is_active"=>0),
    array("code"=>"BAM","name"=>"Bosnia and Herzegovina Convertible Marka","symbol"=>"75","is_active"=>0),
    array("code"=>"BWP","name"=>"Botswana Pula","symbol"=>"80","is_active"=>0),
    array("code"=>"BGN","name"=>"Bulgaria Lev","symbol"=>"1083","is_active"=>0),
    array("code"=>"BRL","name"=>"Brazil Real","symbol"=>"82","is_active"=>0),
    array("code"=>"BND","name"=>"Brunei Darussalam Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"KHR","name"=>"Cambodia Riel","symbol"=>"6107","is_active"=>0),
    array("code"=>"CAD","name"=>"Canada Dollar","symbol"=>"36","is_active"=>1),
    array("code"=>"KYD","name"=>"Cayman Islands Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"CLP","name"=>"Chile Peso","symbol"=>"36","is_active"=>0),
    array("code"=>"CNY","name"=>"China Yuan Renminbi","symbol"=>"165","is_active"=>0),
    array("code"=>"COP","name"=>"Colombia Peso","symbol"=>"36","is_active"=>0),
    array("code"=>"CRC","name"=>"Costa Rica Colon","symbol"=>"8353","is_active"=>0),
    array("code"=>"HRK","name"=>"Croatia Kuna","symbol"=>"107","is_active"=>0),
    array("code"=>"CUP","name"=>"Cuba Peso","symbol"=>"8369","is_active"=>0),
    array("code"=>"CZK","name"=>"Czech Republic Koruna","symbol"=>"75","is_active"=>0),
    array("code"=>"DKK","name"=>"Denmark Krone","symbol"=>"107","is_active"=>0),
    array("code"=>"DOP","name"=>"Dominican Republic Peso","symbol"=>"82","is_active"=>0),
    array("code"=>"XCD","name"=>"East Caribbean Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"EGP","name"=>"Egypt Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"SVC","name"=>"El Salvador Colon","symbol"=>"36","is_active"=>0),
    array("code"=>"EEK","name"=>"Estonia Kroon","symbol"=>"107","is_active"=>0),
    array("code"=>"EUR","name"=>"Euro Member country","symbol"=>"8364","is_active"=>1),
    array("code"=>"FKP","name"=>"Falkland Islands (Malvinas) Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"FJD","name"=>"Fiji Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"GHC","name"=>"Ghana Cedis","symbol"=>"162","is_active"=>0),
    array("code"=>"GIP","name"=>"Gibraltar Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"GTQ","name"=>"Guatemala Quetzal","symbol"=>"81","is_active"=>0),
    array("code"=>"GGP","name"=>"Guernsey Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"GYD","name"=>"Guyana Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"HNL","name"=>"Honduras Lempira","symbol"=>"76","is_active"=>0),
    array("code"=>"HKD","name"=>"Hong Kong Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"HUF","name"=>"Hungary Forint","symbol"=>"70","is_active"=>0),
    array("code"=>"ISK","name"=>"Iceland Krona","symbol"=>"107","is_active"=>0),
    array("code"=>"INR","name"=>"India Rupee","symbol"=>"","is_active"=>0),
    array("code"=>"IDR","name"=>"Indonesia Rupiah","symbol"=>"82","is_active"=>0),
    array("code"=>"IRR","name"=>"Iran Rial","symbol"=>"65020","is_active"=>0),
    array("code"=>"IMP","name"=>"Isle of Man Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"ILS","name"=>"Israel Shekel","symbol"=>"8362","is_active"=>0),
    array("code"=>"JMD","name"=>"Jamaica Dollar","symbol"=>"74","is_active"=>0),
    array("code"=>"JPY","name"=>"Japan Yen","symbol"=>"165","is_active"=>0),
    array("code"=>"JEP","name"=>"Jersey Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"KZT","name"=>"Kazakhstan Tenge","symbol"=>"1083","is_active"=>0),
    array("code"=>"KPW","name"=>"Korea (North) Won","symbol"=>"8361","is_active"=>0),
    array("code"=>"KRW","name"=>"Korea (South) Won","symbol"=>"8361","is_active"=>0),
    array("code"=>"KGS","name"=>"Kyrgyzstan Som","symbol"=>"1083","is_active"=>0),
    array("code"=>"LAK","name"=>"Laos Kip","symbol"=>"8365","is_active"=>0),
    array("code"=>"LVL","name"=>"Latvia Lat","symbol"=>"76","is_active"=>0),
    array("code"=>"LBP","name"=>"Lebanon Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"LRD","name"=>"Liberia Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"LTL","name"=>"Lithuania Litas","symbol"=>"76","is_active"=>0),
    array("code"=>"MKD","name"=>"Macedonia Denar","symbol"=>"1076","is_active"=>0),
    array("code"=>"MYR","name"=>"Malaysia Ringgit","symbol"=>"82","is_active"=>0),
    array("code"=>"MUR","name"=>"Mauritius Rupee","symbol"=>"8360","is_active"=>0),
    array("code"=>"MXN","name"=>"Mexico Peso","symbol"=>"36","is_active"=>0),
    array("code"=>"MNT","name"=>"Mongolia Tughrik","symbol"=>"8366","is_active"=>0),
    array("code"=>"MZN","name"=>"Mozambique Metical","symbol"=>"77","is_active"=>0),
    array("code"=>"NAD","name"=>"Namibia Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"NPR","name"=>"Nepal Rupee","symbol"=>"8360","is_active"=>0),
    array("code"=>"ANG","name"=>"Netherlands Antilles Guilder","symbol"=>"402","is_active"=>0),
    array("code"=>"NZD","name"=>"New Zealand Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"NIO","name"=>"Nicaragua Cordoba","symbol"=>"67","is_active"=>0),
    array("code"=>"NGN","name"=>"Nigeria Naira","symbol"=>"8358","is_active"=>0),
    array("code"=>"KPW","name"=>"Korea (North) Won","symbol"=>"8361","is_active"=>0),
    array("code"=>"NOK","name"=>"Norway Krone","symbol"=>"107","is_active"=>0),
    array("code"=>"OMR","name"=>"Oman Rial","symbol"=>"65020","is_active"=>0),
    array("code"=>"PKR","name"=>"Pakistan Rupee","symbol"=>"8360","is_active"=>0),
    array("code"=>"PAB","name"=>"Panama Balboa","symbol"=>"66","is_active"=>0),
    array("code"=>"PYG","name"=>"Paraguay Guarani","symbol"=>"71","is_active"=>0),
    array("code"=>"PEN","name"=>"Peru Nuevo Sol","symbol"=>"83","is_active"=>0),
    array("code"=>"PHP","name"=>"Philippines Peso","symbol"=>"8369","is_active"=>0),
    array("code"=>"PLN","name"=>"Poland Zloty","symbol"=>"122","is_active"=>0),
    array("code"=>"QAR","name"=>"Qatar Riyal","symbol"=>"65020","is_active"=>0),
    array("code"=>"RON","name"=>"Romania New Leu","symbol"=>"108","is_active"=>0),
    array("code"=>"RUB","name"=>"Russia Ruble","symbol"=>"1088","is_active"=>0),
    array("code"=>"SHP","name"=>"Saint Helena Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"SAR","name"=>"Saudi Arabia Riyal","symbol"=>"65020","is_active"=>0),
    array("code"=>"RSD","name"=>"Serbia Dinar","symbol"=>"1044","is_active"=>0),
    array("code"=>"SCR","name"=>"Seychelles Rupee","symbol"=>"8360","is_active"=>0),
    array("code"=>"SGD","name"=>"Singapore Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"SBD","name"=>"Solomon Islands Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"SOS","name"=>"Somalia Shilling","symbol"=>"83","is_active"=>0),
    array("code"=>"ZAR","name"=>"South Africa Rand","symbol"=>"82","is_active"=>0),
    array("code"=>"KRW","name"=>"Korea (South) Won","symbol"=>"8361","is_active"=>0),
    array("code"=>"LKR","name"=>"Sri Lanka Rupee","symbol"=>"8360","is_active"=>0),
    array("code"=>"SEK","name"=>"Sweden Krona","symbol"=>"107","is_active"=>0),
    array("code"=>"CHF","name"=>"Switzerland Franc","symbol"=>"67","is_active"=>0),
    array("code"=>"SRD","name"=>"Suriname Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"SYP","name"=>"Syria Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"TWD","name"=>"Taiwan New Dollar","symbol"=>"78","is_active"=>0),
    array("code"=>"THB","name"=>"Thailand Baht","symbol"=>"3647","is_active"=>0),
    array("code"=>"TTD","name"=>"Trinidad and Tobago Dollar","symbol"=>"84","is_active"=>0),
    array("code"=>"TRY","name"=>"Turkey Lira","symbol"=>"","is_active"=>0),
    array("code"=>"TRL","name"=>"Turkey Lira","symbol"=>"8356","is_active"=>0),
    array("code"=>"TVD","name"=>"Tuvalu Dollar","symbol"=>"36","is_active"=>0),
    array("code"=>"UAH","name"=>"Ukraine Hryvna","symbol"=>"8372","is_active"=>0),
    array("code"=>"GBP","name"=>"United Kingdom Pound","symbol"=>"163","is_active"=>0),
    array("code"=>"USD","name"=>"United States Dollar","symbol"=>"36","is_active"=>1),
    array("code"=>"UYU","name"=>"Uruguay Peso","symbol"=>"36","is_active"=>0),
    array("code"=>"UZS","name"=>"Uzbekistan Som","symbol"=>"1083","is_active"=>0),
    array("code"=>"VEF","name"=>"Venezuela Bolivar","symbol"=>"66","is_active"=>0),
    array("code"=>"VND","name"=>"Viet Nam Dong","symbol"=>"8363","is_active"=>0),
    array("code"=>"YER","name"=>"Yemen Rial","symbol"=>"65020","is_active"=>0),
    array("code"=>"ZWD","name"=>"Zimbabwe Dollar","symbol"=>"90","is_active"=>0),
);
/*EOF*/